import ConfigStyled from './Config.styled';

const { FONT } = ConfigStyled;
const { COLORS_BRAND, COLORS_NEUTRAL } = ConfigStyled.COLORS;

export default (): object => {
  return {
    FONT: {
      DEFAULT: `'${FONT.DEFAULT}', sans-serif`,
    },
    COLOR: {
      FOREGROUND0: COLORS_NEUTRAL.NEUTRAL0,
      FOREGROUND1: COLORS_NEUTRAL.NEUTRAL50,
      FOREGROUND2: COLORS_NEUTRAL.NEUTRAL100,
      FOREGROUND3: COLORS_NEUTRAL.NEUTRAL200,
      FOREGROUND4: COLORS_NEUTRAL.NEUTRAL300,
      FOREGROUND5: COLORS_NEUTRAL.NEUTRAL400,
      BACKGROUND0: COLORS_NEUTRAL.NEUTRAL1000,
      BACKGROUND1: COLORS_NEUTRAL.NEUTRAL950,
      BACKGROUND2: COLORS_NEUTRAL.NEUTRAL900,
      BACKGROUND3: COLORS_NEUTRAL.NEUTRAL800,
      BACKGROUND4: COLORS_NEUTRAL.NEUTRAL700,
      BACKGROUND5: COLORS_NEUTRAL.NEUTRAL600,
      BORDER: COLORS_NEUTRAL.NEUTRAL500,
      ERROR: '#AE2E24',
      THEME: COLORS_BRAND.BRAND400,
      PRIMARY: COLORS_BRAND.BRAND600,
      SECONDARY: COLORS_BRAND.BRAND100,
    },
  };
};
